version: 1
runners:
  Machine:
    config-id: 2
images:
  DeployMachine:
    image: zenithstar/zcatalyst-cli:test
    auth:
      username: << env.USER_NAME >>
      password: << env.USER_PASSWORD >>
jobs:
  Deploy_Client_Functions:
    steps:
      - apt-get update 
      - apt-get -y install openjdk-17-jdk curl
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash - 
      - apt-get install -y nodejs
      - apt-get update && \
      - apt-get install -y software-properties-common wget curl && \
      - add-apt-repository ppa:deadsnakes/ppa && \
      - apt-get update && \
      - apt-get install -y python3.9 python3.9-distutils && \
      - wget https://bootstrap.pypa.io/get-pip.py && \
      - python3.9 get-pip.py && \
      - rm get-pip.py
      - npm i -g zcatalyst-cli
      - catalyst -v
      - cd functions/Node
      - npm install
      - cd ../..
      - catalyst deploy --project << env.PROJECT_NAME >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>
stages:
  - name: build
    image: DeployMachine
    jobs:
      - Deploy_Client_Functions