version: 1
runners:
  Machine:
    config-id: 2
images:
  DeployMachine:
    image: Ubuntu
    auth:
      username: prabhu
      password: Catalyst@123
  Node:
    image: node:18
    auth:
      username: prabhu
      password: Catalyst@123
  Java:
    image: openjdk:17
    auth:
      username: prabhu
      password: Catalyst@123
  Python:
    image: python:3.9
    auth:
      username: prabhu
      password: Catalyst@123
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
  Install-CatalystCLI:
    image: Node
    steps:
      - npm i -g zcatalyst-cli
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world
      - Install-CatalystCLI