version: 1
runners:
  Machine:
    config-id: 2
images:
  DeployMachine:
    image: ubuntu
    auth:
      username: prabhu16357
      password: Catalyst@123
  Node:
    image: node:18
    auth:
      username: prabhu16357
      password: Catalyst@123
  Java:
    image: openjdk:17
    auth:
      username: prabhu16357
      password: Catalyst@123
  Python:
    image: python:3.9
    auth:
      username: prabhu16357
      password: Catalyst@123
jobs:
  Install-CatalystCLI:
    steps:
      - npm i -g zcatalyst-cli
      - catalyst -v
  NodePackageInstall:
    steps:
        - cd functions/Node
        - npm install
  CLIDeploy:
    steps:
      - catalyst deploy --project << env.PROJECT_NAME >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>
  Node_Java_Python_Install:
    steps:
      - apt-get update 
      - apt-get -y install openjdk-8-jdk curl
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash - 
      - apt-get install -y nodejs
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:deadsnakes/ppa
      - apt-get update
      - apt-get install -y python3.9
      - npm i -g zcatalyst-cli
      - catalyst -v
      - cd functions/Node
      - npm install
      - catalyst deploy --project << env.PROJECT_NAME >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>
stages:
  - name: build
    image: DeployMachine
    jobs:
      - Node_Java_Python_Install