version: 1
runners:
  Machine:
    config-id: 2
images:
  DeployMachine:
    image: Ubuntu
    auth:
      username: prabhu16357
      password: Catalyst@123
  Node:
    image: node:18
    auth:
      username: prabhu16357
      password: Catalyst@123
  Java:
    image: openjdk:17
    auth:
      username: prabhu16357
      password: Catalyst@123
  Python:
    image: python:3.9
    auth:
      username: prabhu16357
      password: Catalyst@123
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
  Install-CatalystCLI:
    steps:
      - npm i -g zcatalyst-cli
      - catalyst -v
  NodePackageInstall:
    steps:
        - cd functions/Node
        - npm install
        
stages:
  - name: build
    image: Node
    jobs:
      - - Install-CatalystCLI
        - NodePackageInstall