version: 1
runners:
  Machine:
    config-id: 3
# images:
#   DeployMachine:
#     image: ubuntu
#     auth:
#       username: << env.USER_NAME >>
#       password: << env.USER_PASSWORD >>
jobs:
  UploadStatus:
    artifacts:
      upload:
        - type: zip
          regex:
            - /catalyst/client/**
          name: test
          location: stratus://pipeline-upload/
    notify:
      on-start:
        email:
          to:
            - prabhu.raam@zohocorp.com
      on-end:
        email:
          to:
            - prabhu.raam@zohocorp.com
    steps:
      - pwd
      - cd client

#   DeployClientApproval:
#     type: approval
#     specification:
#       reviewers:
#         - prabhu.raam+16@zohotest.com
#       message: New Client added

  Deploy_Client_Functions:
    runner: Machine
    steps:
      - apt-get update
      - apt-get -y install openjdk-17-jdk curl
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
      - apt-get update && \
      - apt-get install -y software-properties-common wget curl && \
      - add-apt-repository ppa:deadsnakes/ppa && \
      - apt-get update && \
      - apt-get install -y python3.9 python3.9-distutils && \
      - wget https://bootstrap.pypa.io/get-pip.py && \
      - python3.9 get-pip.py && \
      - rm get-pip.py
      - npm i -g zcatalyst-cli
      - catalyst -v
      - cd functions/Node
      - npm install
      - cd ../..
      - printenv
      - catalyst deploy --project << env.PROJECT_ID >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>

#   downloadArtifact:
#     artifacts:
#       download:
#         - type: zip
#           name: client.zip
#           location: stratus://pipeline-upload/
#           file: /catalyst/test/
#     runner: Machine
#     steps:
#       - pwd
#       - ls


stages:
  - name: build
    # image: DeployMachine
    jobs:
    #   - UploadStatus
    #   - DeployClientApproval
    #   - downloadArtifact
      - Deploy_Client_Functions