name: Create Release
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Loading Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      # - name: Loading Java17
      #   uses: actions/setup-java@v4.0.0
      #   with:
      #     java-version: '17'
      #     distribution: 'oracle'
      - name: Installing catalyst
        run : npm i -g zcatalyst-cli
      - name: "Logging Current Dir"
        run : cd .. && ls
      - name: Installing Packages for 'Node'
        run: cd functions/Node/ && npm install --omit=dev
      - name: Deploying code to catalyst
        run: catalyst deploy --project ${{ secrets.CATALYST_PROJECT_NAME}} --org ${{ secrets.CATALYST_ORG}} --token ${{ secrets.CATALYST_TOKEN}}
